name: Automate test CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      env:
        HOST: '0.0.0.0'
        PORT: '1337'
        APP_KEYS: 'mock'
        API_TOKEN_SALT: 'mock'
        ADMIN_JWT_SECRET: 'mock'
        TRANSFER_TOKEN_SALT: 'mock'
        DATABASE_CLIENT: 'mock'
        DATABASE_FILENAME: 'mock'
        JWT_SECRET: 'mock'

    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - run: yarn test
